backend:
  name: github
  repo: Vorschlag-bit/blog
  branch: main
  # 로컬 환경 테스트
  base_url: http://localhost:3000
  # base_url: https://vorschlag-blog.vercel.app/
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts" # 마크다운 파일이 저장되는 실제 폴더 경로
    create: true
    slug: "{{slug}}" # 파일명 규칙
    fields: # 마크다운 Frontmatter랑 1:1 매칭 시킴
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}